### ISSUE TITLE
buld error

### ISSUE THREAD

**Issue by DesSolo** [bluecherrydvr/bluecherry-docker#3] opened 2020-06-11 12:11 UTC
`podman-compose build`
```
dpkg: error processing package bluecherry (--configure):
 installed bluecherry package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for libapache2-mod-php7.2 (7.2.24-0ubuntu0.18.04.6) ...
Errors were encountered while processing:
 bluecherry
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: error building at STEP "RUN /usr/sbin/groupadd -r -f -g $BLUECHERRY_GROUP_ID bluecherry &&     useradd -c "Bluecherry DVR" -d /var/lib/bluecherry -g bluecherry -G audio,video -r -m bluecherry -u $BLUECHERRY_USER_ID &&     {         echo "[client]";                                echo "user=$MYSQL_ADMIN_LOGIN";                 echo "password=$MYSQL_ADMIN_PASSWORD";          echo "[mysql]";                                 echo "user=$MYSQL_ADMIN_LOGIN";                 echo "password=$MYSQL_ADMIN_PASSWORD";          echo "[mysqldump]";                             echo "user=$MYSQL_ADMIN_LOGIN";                 echo "password=$MYSQL_ADMIN_PASSWORD";          echo "[mysqldiff]";                             echo "user=$MYSQL_ADMIN_LOGIN";                 echo "password=$MYSQL_ADMIN_PASSWORD";      } > /root/.my.cnf                           &&     apt-get update                              &&     {         echo bluecherry bluecherry/mysql_admin_login password $MYSQL_ADMIN_LOGIN;               echo bluecherry bluecherry/mysql_admin_password password $MYSQL_ADMIN_PASSWORD;         echo bluecherry bluecherry/db_host string $host;                                        echo bluecherry bluecherry/db_userhost string $userhost;                                echo bluecherry bluecherry/db_name string $dbname;                                      echo bluecherry bluecherry/db_user string $user;                                        echo bluecherry bluecherry/db_password password $password;                          } | debconf-set-selections  &&         apt -y install wget gnupg supervisor &&     wget -q https://dl.bluecherrydvr.com/key/bluecherry.asc &&     apt-key add bluecherry.asc &&     wget --no-check-certificate --output-document=/etc/apt/sources.list.d/bluecherry-bionic.list https://dl.bluecherrydvr.com/sources.list.d/bluecherry-bionic-unstable.list &&     apt-get update &&     apt --no-install-recommends -y install rsyslog mysql-client bluecherry": error while running runtime: exit status 100
125
```

**Comment by thelosmos** [comment] 2020-08-05 13:59
It appears that I am experiencing this same issue. Please let me know anyway I an help.

**Comment by curtishall** [comment] 2020-09-02 03:05
Using docker-compose build I'm unable to reproduce this error.

**Comment by RichieFrame** [comment] 2020-09-23 10:56
I am getting the exact same error using docker-compose, prior to this error, the following error messages appears in the build:

```
+ echo 'Testing whether database already exists...'
Testing whether database already exists...
+ echo 'show databases'
+ mysql_wrapper -hmysql -uroot -Dbluecherry
+ echo -e '\n\n\tDatabase '\''bluecherry'\'' already exists, but /etc/bluecherry.conf is not found.'


        Database 'bluecherry' already exists, but /etc/bluecherry.conf is not found.
+ echo -e '\tAborting installation. In order to proceed installation, please do one of following things:\n' '\t * Restore /etc/bluecherry.conf config file if it was removed, template is in /usr/share/bluecherry/bluecherry.conf.in;\n'
        Aborting installation. In order to proceed installation, please do one of following things:
         * Restore /etc/bluecherry.conf config file if it was removed, template is in /usr/share/bluecherry/bluecherry.conf.in;

+ [[ -n IN_DEB ]]
+ echo -e '\t * Accomplish removal of previous setup by '\''apt-get remove --purge bluecherry'\'';\n'
         * Accomplish removal of previous setup by 'apt-get remove --purge bluecherry';

+ echo -e '\t * Remove the database '\''bluecherry'\'' manually.\n\n'
         * Remove the database 'bluecherry' manually.


+ exit 1
++ exit 1
dpkg: error processing package bluecherry (--configure):
 installed bluecherry package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
Processing triggers for libapache2-mod-php7.2 (7.2.24-0ubuntu0.18.04.6) ...
Errors were encountered while processing:
 bluecherry
```

**Comment by RichieFrame** [comment] 2020-09-23 11:23
And if you try to install it with a focal docker image:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bluecherry : Depends: libmysqlclient20 (>= 5.7.11) but it is not installable
              Depends: libopencv-core3.2 but it is not installable
              Depends: libopencv-imgproc3.2 but it is not installable
```

opencv is at 4.2 in focal, and it uses libmysqlclient21 not 20, did see that focal has been added to the distro list, but the deps are not correct

**Comment by curtishall** [comment] 2020-09-29 00:31
It appears that the bluecherry database already exists.

Can you delete both bluecherry and mysql docker images then follow the steps again?  I just build this on a virgin install of Linux Mint 20 without any issues.

Thanks

**Comment by ark4n631** [comment] 2021-02-09 22:31
I think the problem is that the build process of the docker image is expecting the mysql service to be up and running, i fixed by launching the mysql first then building...
`docker-compose up -d mysql`
`docker-compose up -d --build bluecherry`

Although it's cool that's verify it's going to work (because it checks if the mysql is working), build process are usually expecting not to have any service up and running prior launch (like offline building)

Anyways i hope it helps someone else!

Happy hacking :-)

**Comment by curtishall** [comment] 2023-07-04 21:01
See the scripts/install.sh for an automated process

**Closed by curtishall** 2023-07-04 21:01 UTC
